apiVersion: batch/v1
kind: Job
metadata:
  name: pipeline-orchestrator-main
spec:
  template:
    spec:
      containers:
      - name: orchestrator
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
