apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vanguard-health

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - mongo-deployment.yaml
  - redis-deployment.yaml
  - nodeport-services.yaml
  - pipeline-trigger-cronjob.yaml

commonLabels:
  app: vanguard-health
  version: v1.0.0

commonAnnotations:
  description: "Vanguard Health - FHIR Healthcare Data Pipeline"
  managed-by: "kubectl"
