apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-fetch-workers
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
