apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vanguard-health

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: dev-mongodb
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
  - target:
      kind: Deployment
      name: fhir-fetch-workers
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "2Gi"
